# Generated by Django 2.1.7 on 2019-03-17 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 3, 17, 8, 26, 52, 271481, tzinfo=utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_engine.User')),
                ('subscribers', models.ManyToManyField(related_name='subscriptions', to='blog_engine.User')),
            ],
        ),
    ]
