# Generated by Django 2.1.7 on 2019-03-18 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0003_auto_20190317_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_engine.User')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_engine.Blog')),
                ('likes', models.ManyToManyField(related_name='likes', to='blog_engine.User')),
            ],
        ),
    ]
